### ISSUE TITLE
Updates to later versions of gpii-webdriver cause the tests to time out.

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/codemirror-infusion#11]
When updating codemirror-infusion's dependencies to the latest versions, I tried to use the latest dev release of gpii-webdriver, which is listed on the npm registry as <code>1.0.0-dev.20161125T164054Z.becc872</code>.

However, when I run the test suite, the first test doesn't successfully run, and just times out. Here's the log:

$ yarn test
yarn test v0.17.8
$ node tests/all-tests.js 
Infusion at path /Users/colin/code/codemirror-infusion/node_modules/infusion is at top level 
23:22:41.244:  Registering module codemirror-infusion from path /Users/colin/code/codemirror-infusion
23:22:41.246:  Registering module infusion from path /Users/colin/code/codemirror-infusion/node_modules/infusion
23:22:41.246:  Registering module infusion from path /Users/colin/code/codemirror-infusion/node_modules/infusion
23:22:41.255:  Registering module kettle from path /Users/colin/code/codemirror-infusion/node_modules/kettle
23:22:41.399:  Registering module gpii-express from path /Users/colin/code/codemirror-infusion/node_modules/gpii-express
23:22:41.541:  Registering module gpii-webdriver from path /Users/colin/code/codemirror-infusion/node_modules/gpii-webdriver
23:22:41.661:  Successfully queued test chrome: Focus on the editor...
23:22:41.662:  Successfully queued test chrome: Leave the editor when there is a next element to focus on...
23:22:41.663:  Successfully queued test chrome: Leave the editor when there is an earlier element in the body to focus on...
23:22:41.664:  Successfully queued test chrome: Attempt to leave the editor when there is no other focusable element...
23:22:48.433:  Test case listener has not responded after 5000ms - at sequence pos 5 of 8 sequence element {
    "event": "{testEnvironment}.webdriver.events.onActionsHelperComplete",
    "listener": "{testEnvironment}.webdriver.findElement",
    "args": [
        {
            "css": "#editor textarea"
        }
    ]
} of fixture chrome: Focus on the editor...
✨  Done in 7.45s.

Interestingly, <code>yarn test</code> (as well as <code>npm test</code> doesn't seem to report this as a failure. It just dies successfully.

@the-t-in-rtf, do you have any suggestions on what needs to be done to make these tests work with a modern dev release of gpii-webdriver?

**Comment by the-t-in-rtf** [comment]
Is there a branch I can check out to see the problem?

**Comment by the-t-in-rtf** [comment]
Off the top of my head, that usually happens when the element isn't found, and elements have to be visible to be found, but I can confirm with a branch to check out.  You can listen for 'onError' if you want to confirm that it's trying to find the element (and failing).

**Comment by colinbdclark** [comment]
You can see the issue in my [gh-11](https://github.com/colinbdclark/codemirror-infusion/tree/gh-11) branch.
