### ISSUE TITLE
Add a standard index.js file with a call to `fluid.registerModule`...

### ISSUE THREAD

**Issue by the-t-in-rtf** [colinbdclark/codemirror-infusion#8]
In working with this package in the sandbox, it'd be helpful to have an index.js that registers the package content under the `%codemirror-infusion` package name, so that I can reference
content with package-relative paths in various includes.

Colin and I have also discussed a quick haircut, checking the deps and modernizing the lint infrastructure.

**Comment by colinbdclark** [comment]
Thanks for the fix, @the-t-in-rtf, and sorry for taking so long to review and merge this!
